name: coverage CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn --ignore-engines
      - run: yarn run test:coverage
        env:
          CI: true
          PROGRESS: none
          NODE_ENV: test
